In [1]:
import numpy as np
import random
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.utils import *
from sklearn import model_selection
import os

In [2]:
# need to add a way to get all of the csv files to be inputted together so the array is one massive dataset...
# also need to find a way to get the data to be random? but stay as a whole trial

In [3]:
# classifierKey = []
# for i in range(npArray.shape[0]):
#     classifierKey.append(npArray[i][1])
    
#     # idea- I need to get the data into a format where all of the electrodes of the same trial
#     # are in the same array. Then I need to get all of the classifiers into a list and number them?

In [4]:
# parse the txt data to get an array of arrays with only the desired electrodes
conditionList = []
electrodeData = []
allData = []
for file in os.listdir('/Volumes/Amelia\'s Backups/thesisData'):
    print("loading " + file)
    f = open("/Volumes/Amelia\'s Backups/thesisData/"+file, "r")
    lines = f.readlines()
    trialNum = 0
    for line in lines:
        vals = line.split(",")
        if trialNum != vals[2] and vals[2]!="trial": # added this to see if fixes error
            #print(trialNum)
            trialNum = vals[2] #this is the new trial number
            #we need a new electrode data list bc a new trial is started
            # somehow filter the first line
            if len(electrodeData)>4:
                allData.append(electrodeData)
                conditionList.append(vals[1])
            electrodeData = []
            #conditionList.append(vals[1])
            #then append all the values of interest to the newly empty list or append to a nonempty list
        if vals[2]!="trial":
            electrodeData.append(float(vals[33]))
            electrodeData.append(float(vals[35]))
            electrodeData.append(float(vals[46]))
            electrodeData.append(float(vals[47]))
    allData.append(electrodeData)
    conditionList.append(vals[1])

loading 101.txt
loading 102.txt
loading 103.txt
loading 104.txt
loading 105.txt
loading 106.txt
loading 107.txt
loading 108.txt
loading 109.txt
loading 110.txt
loading 111.txt
loading 112.txt
loading 113.txt
loading 114.txt
loading 115.txt
loading 116.txt
loading 118.txt
loading 119.txt
loading 120.txt
loading 121.txt
loading 122.txt
loading 123.txt
loading 124.txt
loading 125.txt
loading 126.txt
loading 127.txt
loading 128.txt
loading 129.txt
loading 130.txt
loading 131.txt
loading 132.txt
loading 133.txt
loading 134.txt
loading 136.txt
loading 137.txt
loading 138.txt
loading 139.txt
loading 140.txt
loading 141.txt
loading 142.txt
loading 143.txt
loading 144.txt
loading 145.txt
loading 147.txt
loading 148.txt
loading 149.txt
loading 150.txt
loading 151.txt
loading 152.txt
loading 153.txt
loading 154.txt
loading 155.txt
loading 156.txt
loading 158.txt
loading 159.txt
loading 160.txt


In [5]:
print(len(conditionList))

42687


In [14]:
# make the conditions list fit a numerical schema
numCond = []
for item in conditionList:
    if item=="House upright ":
        numCond.append(0)
    elif item=="House invert":
        numCond.append(1)
    elif item=="Face White upright 0%":
        numCond.append(2)
    elif item=="Face White Invert 0%":
        numCond.append(3)
    elif item=="Face White upright 70%":
        numCond.append(4)
    elif item=="Face White invert 70%":
        numCond.append(5)
    elif item=="Face Black upright 0%":
        numCond.append(6)
    elif item=="Face Black Invert 0%":
        numCond.append(7)
    elif item=="Face Black upright 70%":
        numCond.append(8)
    elif item=="Face Black Invert 70%":
        numCond.append(9)

In [15]:
# numCond = []
# for item in conditionList:
#     if item=="House upright ":
#         numCond.append(0)
#     elif item=="House invert":
#         numCond.append(0)
#     elif item=="Face White upright 0%":
#         numCond.append(1)
#     elif item=="Face White Invert 0%":
#         numCond.append(1)
#     elif item=="Face White upright 70%":
#         numCond.append(1)
#     elif item=="Face White invert 70%":
#         numCond.append(1)
#     elif item=="Face Black upright 0%":
#         numCond.append(1)
#     elif item=="Face Black Invert 0%":
#         numCond.append(1)
#     elif item=="Face Black upright 70%":
#         numCond.append(1)
#     elif item=="Face Black Invert 70%":
#         numCond.append(1)

In [16]:
print(len(numCond))

42687


In [17]:
npArr = np.array(allData, dtype=object)
print(npArr)

[[-1.464439 0.689703 7.864256 ... -1.96993 8.47317 8.952189]
 [2.059378 1.850796 4.45815 ... 6.729721 -0.501504 0.219612]
 [-0.057974 1.094998 -7.128395 ... 4.657661 -6.681059 -7.257719]
 ...
 [-6.704969 -8.925579 26.868647 ... 6.116722 17.14164 -5.441307]
 [14.802292 12.661365 27.215427 ... 28.800381 -57.027412 14.169834]
 [2.151755 8.268625 -62.196735 ... 39.227005 -88.654099 10.256313]]


In [18]:
npNumCond = np.array(numCond)

X, y = shuffle(npArr, npNumCond, random_state=0)
print(X)
print(y)

[[2.203053 1.498927 8.738965 ... -3.119158 -4.52574 -5.340775]
 [-3.996404 -8.275059 -10.778839 ... -9.10048 -14.547396 -1.66135]
 [4.685529 3.064858 -1.748873 ... -4.832255 -2.238585 -1.221576]
 ...
 [20.66337 19.609638 -10.844703 ... -1.68988 -0.000885 0.980953]
 [-237.81665 -237.621796 -293.90271 ... 0.513733 53.161804 27.596466]
 [7.62851 8.845196 4.357373 ... -0.607235 2.400339 2.656394]]
[0 8 6 ... 6 0 1]


In [19]:
#TRAINING
#X, y = shuffle(npArr, npNumCond, random_state=0)
split = model_selection.train_test_split(X, y, test_size=0.2, train_size=0.8, random_state=None, shuffle=True, stratify=None)
Xtrain = split[0]
Xtest = split[1]
ytrain = split[2]
ytest = split[3]
clf = LinearDiscriminantAnalysis()
clf.fit(Xtrain, ytrain)

LinearDiscriminantAnalysis()

In [22]:
#TESTING
predictions=[]
correct = 0
for i in range(len(Xtest)):
    sample = Xtest[i].reshape(1,-1)
    prediction = clf.predict(sample)
    prediction = prediction[0]
    predictions.append(prediction)
    if prediction==ytest[i]:
        correct+=1
print(correct)
print(len(Xtest))
accuracy = correct/len(ytest)
print(accuracy)

2145
8538
0.2512297962052003


In [21]:
print(predictions)

[1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 9, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 2, 1, 1, 0, 0, 1, 1, 1, 1, 0, 9, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 6, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 4, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 2, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 2, 1, 0, 0, 0, 0, 0, 5, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 